FROM node:18

WORKDIR /app

# Copy package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the code
COPY . .

RUN npx run build

EXPOSE 3000

CMD [ "npx","serve","-s","dist" ]