FROM node:18

WORKDIR /app

# Copy package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the code
COPY . .

# Expose backend port
EXPOSE 5000

# Start the backend in production mode
CMD ["npm", "run", "prod"]
